### PR TITLE
chore: fix linting errors

### PR DESCRIPTION
**Pull request by ns-rse**
Fixes a bunch of linting errors, some notes left in place for tasks to be completed (e.g. see #899).

### CODE REVIEW

**Comment by SylviaWhittle** [comment]
(I could have messed something up)

When I checked out this branch and ran `toposats process --config topostats/default_config.yaml`, I get the following error:

```
[Mon, 16 Sep 2024 15:41:39] [WARNING ] [topostats] There are no grainstats or dnatracing statistics to write to CSV.
Traceback (most recent call last):
  File "/Users/sylvi/.pyenv/versions/topo-unet/bin/topostats", line 8, in <module>
    sys.exit(entry_point())
             ^^^^^^^^^^^^^
  File "/Users/sylvi/Documents/TopoStats/topostats/entry_point.py", line 386, in entry_point
    args.func(args)
  File "/Users/sylvi/Documents/TopoStats/topostats/run_topostats.py", line 253, in run_topostats
    save_folder_grainstats(config["output_dir"], config["base_dir"], mols_results)
  File "/Users/sylvi/Documents/TopoStats/topostats/io.py", line 293, in save_folder_grainstats
    dirs = set(all_stats_df["basename"].values)
               ~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/sylvi/.pyenv/versions/topo-unet/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sylvi/.pyenv/versions/topo-unet/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'basename'
```

Could you try the same to see if this is a real error?

**Comment by ns-rse** [comment]
Got the same error will investigate and try and work out a test that captures this as really the test suite should cover all uses and we shouldn't have to run manually to check.

**Comment by ns-rse** [comment]
Its something to do with the grain statistics that are being calculated for the `below` direction.

Adding the following to `topostats/processing.py` at line 334...

```python
            print(f"#### GRAINSTATS {grainstats_df=}")
            print(f"#### GRAINSTATS {grainstats_dict['above']=}")
            print(f"#### GRAINSTATS {grainstats_dict['below']=}")
```
 The `above` data frame is printed but the `below` print results in the following...

```
[Mon, 16 Sep 2024 19:03:35] [INFO    ] [topostats] [minicircle] : Processing grain: 20
#### GRAINSTATS START grainstats_df=Empty DataFrame
Columns: [image, basename, area, area_cartesian_bbox, aspect_ratio, bending_angle, centre_x, centre_y, circular, contour_length, end_to_end_distance, height_max, height_mean, height_median, height_min, max_feret, min_feret, radius_max, radius_mean, radius_median, radius_min, smallest_bounding_area, smallest_bounding_length, smallest_bounding_width, threshold, volume]
Index: []
#### GRAINSTATS START grainstats_dict['above']=                  centre_x      centre_y    radius_min    radius_max   radius_mean  radius_median    height_min    height_max  height_median   height_mean  ...          area  area_cartesian_bbox  smallest_bounding_width  smallest_bounding_length  smallest_bounding_area  aspect_ratio  threshold     max_feret     min_feret       image
grain_number                                                                                                                                                ...                                                                                                                                                                               
0             1.873903e-08  9.654458e-08  5.015176e-09  2.103389e-08  1.529742e-08   1.592692e-08  7.862353e-10  3.930999e-09   2.102850e-09  2.008218e-09  ...  6.376736e-16         1.137465e-15             2.405749e-08              4.124140e-08            9.921645e-16      1.714286      above  4.138436e-08  2.404835e-08  minicircle
1             4.002585e-07  9.313249e-08  1.152687e-09  2.193567e-08  1.383897e-08   1.477475e-08  7.856515e-10  3.203594e-09   2.178474e-09  2.029474e-09  ...  6.335250e-16         1.186029e-15             2.792782e-08              3.962207e-08            1.106558e-15      1.418731      above  3.967123e-08  2.792782e-08  minicircle
2             2.177980e-07  1.731675e-07  7.850032e-09  2.886061e-08  1.778908e-08   1.641640e-08  7.851755e-10  3.137616e-09   2.017664e-09  1.904675e-09  ...  6.247396e-16         1.592842e-15             2.416820e-08              5.458082e-08            1.319120e-15      2.258373      above  5.469842e-08  2.416820e-08  minicircle
3             3.551339e-07  2.059211e-07  3.867795e-09  2.595261e-08  1.609306e-08   1.721738e-08  7.860013e-10  3.120365e-09   2.143942e-09  2.017954e-09  ...  6.157101e-16         1.696558e-15             1.819344e-08              4.950880e-08            9.007352e-16      2.721245      above  4.968108e-08  1.819344e-08  minicircle
4             3.014011e-07  2.116093e-07  9.558786e-09  2.528147e-08  1.787277e-08   1.843296e-08  7.852266e-10  3.009595e-09   1.924296e-09  1.866787e-09  ...  7.218671e-16         1.739509e-15             3.332044e-08              4.395027e-08            1.464442e-15      1.319018      above  4.418497e-08  3.332044e-08  minicircle
5             4.324963e-07  2.157950e-07  2.398779e-09  2.356588e-08  1.505581e-08   1.590801e-08  7.848618e-10  3.244962e-09   2.199464e-09  2.049851e-09  ...  6.161982e-16         1.259241e-15             2.065823e-08              4.594861e-08            9.492169e-16      2.224228      above  4.620710e-08  2.065823e-08  minicircle
6             1.944184e-07  2.312459e-07  8.966634e-09  2.390062e-08  1.796208e-08   1.832216e-08  7.852557e-10  2.931467e-09   2.074074e-09  1.947625e-09  ...  6.881897e-16         1.559409e-15             2.974231e-08              4.527651e-08            1.346628e-15      1.522293      above  4.614368e-08  2.974231e-08  minicircle
7             3.897304e-07  2.743838e-07  1.607555e-09  2.554729e-08  1.653010e-08   1.806594e-08  7.898063e-10  3.053506e-09   2.227060e-09  2.053019e-09  ...  7.033201e-16         1.770258e-15             2.241199e-08              4.910628e-08            1.100570e-15      2.191071      above  4.922213e-08  2.241199e-08  minicircle
8             4.303808e-07  2.959329e-07  2.365908e-09  2.230054e-08  1.526358e-08   1.658750e-08  7.866535e-10  4.414037e-09   2.218955e-09  2.100924e-09  ...  6.603692e-16         1.420794e-15             2.689315e-08              4.172411e-08            1.122093e-15      1.551477      above  4.354237e-08  2.606386e-08  minicircle
9             1.227239e-07  3.088267e-07  8.469838e-09  2.743921e-08  1.764492e-08   1.728073e-08  7.860254e-10  3.059123e-09   2.265093e-09  2.069936e-09  ...  6.906301e-16         1.706320e-15             2.555373e-08              5.220711e-08            1.334087e-15      2.043033      above  5.246906e-08  2.555373e-08  minicircle
10            3.888889e-08  3.823863e-07  1.685375e-09  2.773952e-08  1.663009e-08   1.695792e-08  7.849540e-10  2.967817e-09   2.210113e-09  2.038616e-09  ...  6.662262e-16         1.234837e-15             1.952555e-08              5.456852e-08            1.065480e-15      2.794724      above  5.457559e-08  1.952555e-08  minicircle
11            3.897274e-07  3.775507e-07  9.040455e-09  2.696272e-08  1.741884e-08   1.677701e-08  7.849220e-10  3.044908e-09   2.196166e-09  2.023708e-09  ...  6.628096e-16         1.464233e-15             2.837678e-08              4.850977e-08            1.376551e-15      1.709488      above  4.902839e-08  2.837678e-08  minicircle
12            2.612064e-07  3.747969e-07  5.284144e-09  2.545378e-08  1.739296e-08   1.837059e-08  7.874981e-10  2.937551e-09   2.101391e-09  1.956002e-09  ...  6.933145e-16         1.452520e-15             2.556090e-08              5.001954e-08            1.278544e-15      1.956878      above  5.018690e-08  2.556090e-08  minicircle
13            3.046807e-07  3.911039e-07  1.092448e-08  2.668428e-08  1.830271e-08   1.853028e-08  7.864589e-10  3.083058e-09   2.047869e-09  1.927934e-09  ...  6.679345e-16         1.665565e-15             3.535557e-08              4.204400e-08            1.486490e-15      1.189176      above  4.904581e-08  3.313363e-08  minicircle
14            4.555114e-07  4.280402e-07  3.978434e-09  2.680501e-08  1.654942e-08   1.655489e-08  7.857228e-10  3.990293e-09   2.206537e-09  2.060730e-09  ...  6.515838e-16         1.319762e-15             2.188373e-08              5.173989e-08            1.132262e-15      2.364308      above  5.174076e-08  2.188373e-08  minicircle
15            2.204600e-07  4.181592e-07  3.932534e-09  2.748731e-08  1.684301e-08   1.618500e-08  7.850418e-10  3.201860e-09   2.125881e-09  1.983791e-09  ...  6.925824e-16         1.530124e-15             2.535473e-08              5.126658e-08            1.299850e-15      2.021973      above  5.148307e-08  2.535473e-08  minicircle
16            3.760942e-07  4.281086e-07  7.872403e-09  2.491242e-08  1.867114e-08   1.926822e-08  7.880415e-10  3.096335e-09   2.129600e-09  1.977045e-09  ...  7.135697e-16         1.530124e-15             3.161664e-08              4.678904e-08            1.479313e-15      1.479886      above  4.805051e-08  3.161664e-08  minicircle
17            4.608598e-07  4.586926e-07  7.996801e-09  2.778412e-08  1.729671e-08   1.682794e-08  7.866559e-10  3.137884e-09   2.174385e-09  2.010541e-09  ...  6.357213e-16         1.616514e-15             2.133895e-08              5.270820e-08            1.124738e-15      2.470046      above  5.325388e-08  2.133895e-08  minicircle
18            4.198167e-07  4.563392e-07  9.982818e-09  2.482341e-08  1.819074e-08   1.882873e-08  7.851909e-10  3.060817e-09   2.162497e-09  2.003190e-09  ...  6.881897e-16         1.603336e-15             3.682726e-08              4.142321e-08            1.525503e-15      1.124797      above  4.596617e-08  3.348351e-08  minicircle
19            9.100481e-08  4.689969e-07  4.486772e-09  2.540968e-08  1.627912e-08   1.678333e-08  7.853485e-10  3.023303e-09   2.182583e-09  2.028196e-09  ...  6.747675e-16         1.600163e-15             2.099968e-08              4.876660e-08            1.024083e-15      2.322254      above  4.891627e-08  2.099968e-08  minicircle
20            2.032140e-08  5.007542e-07  1.558019e-09  2.537412e-08  1.581556e-08   1.625252e-08  7.880109e-10  3.083693e-09   2.223962e-09  2.056520e-09  ...  6.271800e-16         1.391022e-15             2.035424e-08              5.020435e-08            1.021871e-15      2.466530      above  5.020878e-08  2.035424e-08  minicircle

[21 rows x 21 columns]
[Mon, 16 Sep 2024 19:03:36] [INFO    ] [topostats] [minicircle] : Errors occurred whilst calculating grain statistics. Returning empty dataframe.
```

I suspect the error lies further back though, probably that no grains are detected in the `below` region. Will need to investigate if anything has changed in the `topostats/default_config.yaml` and dig deeper (good opportunity to investigate using `pdb` under Emacs to debug.

Not entirely sure why this would result in an an empty combined dataframe, most likely though is that you can `pd.concat()` a `None` object with an existing data frame.

Aside : I'll be changing the log message should be a `WARNING`

Beyond my working day now though (and I've other work stuff to organise for the Sheffield R User Group anyway) so a task to be undertaken tomorrow.

**Comment by ns-rse** [comment]
Narrowing this done there is a problem with splining...

```
[Tue, 17 Sep 2024 10:37:48] [INFO    ] [topostats] [minicircle] : *** Splining ***
[Tue, 17 Sep 2024 10:37:48] [INFO    ] [topostats] Splining failed with 'image' - skipping.
```

It seems that `run_splining()` (and a number of the other functions) take `results_df` as an argument and merge the statistics that are returned by the respective functions. 

If there is an exception during splining the `grainstats_additions_image` is returned (which it looks like is _not_ `grainstats`, rather its splining statistics (the term "grainstats additions dataframe" doesn't tell us what additional statistics there are, they come from `topostats.tracing.splining.splining_image()` and are...

+ `total_contour_length`
+ `average_end_to_end_distance`

Perhaps `splining_statistics` would be more descriptive here?

Actually though the error is occurring further back because `splining_image()` calls either `windowTrace()` or `splineTrace()` and one of these calls ordered tracing which fails with...

```
[Tue, 17 Sep 2024 11:03:04] [INFO    ] [topostats] [minicircle] : *** Ordered Tracing ***
[Tue, 17 Sep 2024 11:03:04] [INFO    ] [topostats] Ordered Tracing failed with ordered_tracing_image() got an unexpected keyword argument 'pixel_to_nm_scaling' - skipping.
```

...and I know that as part of the linting in this PR I have removed the unused argument `pixel_to_nm_scaling` so this is likely the source of the problem.

**Review by SylviaWhittle — APPROVED** [review]
Good catch, thank you. This works on my machine now 😃

**Comment by ns-rse** [comment]
Errors are never where you expect them to be!

Thanks for the approval, duly merged, on with more test fixing!

**Pull request merged**
