### PR TITLE
Topotracing flow diagram

### PR DESCRIPTION
**Pull request by ns-rse**
Adds a flow-diagram for the steps in Topotracing, its based on the slide @SylviaWhittle created (see #162) and uses [Mermaid](https://mermaid-js.github.io/) to create the diagrams written in Markdown and converts using the Sphinx plugin [sphixnxongrib-mermaid](https://sphinxcontrib-mermaid-demo.readthedocs.io/en/latest/). Not totally complete, I'd like to tweak colours for sub-graphs and make a few more changes but its a start (being I only looked at Mermaid today for the first time, done similar in LaTeX years ago, it was much more fickle).

### CODE REVIEW

**Comment by ns-rse** [comment]
You can view the flow diagram [here](https://topostats.readthedocs.io/en/ns-rse-162-topotracing-flow-diagram/workflow.html). It's really just a start, I'm not great at choosing colours and it can no doubt be improved :smile:

**Comment by SylviaWhittle** [comment]
Thanks for making this, @ns-rse. I have committed two suggestions, please feel free to reject them if you feel they are unhelpful 😄

**Comment by ns-rse** [comment]
Thanks @SylviaWhittle I'd been trying to slit the `DNA Tracing` sub-graph out but confused myself in doing so, looks much neater and I like the improved colours.

**Review by SylviaWhittle — APPROVED** [review]
Very useful visualisation for new developers / users. I feel this is currently accurate, however will need updating as we develop further.

**Pull request merged**
