### PR TITLE
Make topostats pip installable

### PR DESCRIPTION
**Pull request by bobturneruk**
This pull requests makes topostats pip installable via `pip install -e .` using the package name `topostats` (all lower case). It does not enable `pip install topostats` (i.e. from PyPi). This will require another step to push our package to the index, and we should probably wait for this until we've sorted some of the dependency issues.

The changes are:
- Put the core topostats code into a folder called `topostats` and the utility functions in `utils`.
- Add an `__init__.py` to the `topostats` folder.
- Add a `setup.py` to the repository root.
- Make the `main` function of `pywgytracing.py` into a function called `trace`.
- Rename `pywgytracing.py` `tracing.py` in the module.
- Remove several global variables from the new `tracing.py`.

This should only minimally affect installation (if you're in the cloned repo. folder you don't actually need to pip install), and should not affect how the user operates the software. **I'm keen to know if this is the case!**

This pull request enables:
- Publishing to PyPi at some future point.
- Setting up tests using `pytest` in a conventional way.

### CODE REVIEW

**Comment by bobturneruk** [comment]
The changes to what was `pygwytracing.py` can be more easily seen here:

https://github.com/AFM-SPM/TopoStats/compare/3fe5b00..53e7af1

**Comment by JoeBeton** [comment]
This is nice and would be great to have topostats available on PyPi. 

Something for the future: we can edit the setup.py so that pwgwytracing can be executed from anywhere after installing (I think using entry points keyword in setup.py)

**Comment by bobturneruk** [comment]
Hi @JoeBeton - thanks! The idea was to leave `pygwytracing.py` out of the package, such that it serves as an example of how to call `topostats.tracing.trace()`. I guess if we want people to be able to execute topostats via a single command after pip installing, that's something to explore. There's probably a few ways of doing this. This may be an option https://packaging.python.org/en/latest/guides/installing-stand-alone-command-line-tools/

**Comment by bobturneruk** [comment]
Also (mainly a note to self this) https://docs.python.org/3/library/__main__.html#main-py-in-python-packages

**Comment by bobturneruk** [comment]
Would probably want to take config file as a command line arg.

**Comment by MaxGamill-Sheffield** [comment]
No changes in the produced TopoStats.csv files from before and after this change.

**Comment by bobturneruk** [comment]
That's great. (We will automate that check in a future update.) Did you 😨 try to reinstall?

**Comment by MaxGamill-Sheffield** [comment]
> That's great. (We will automate that check in a future update.) Did you 😨  try to reinstall?

I did reinstall using docker but I did it the normal way but using `git clone ... -b pip`. Is this what you meant or would you like me to try and install using pip? - if so I may need instructions for this

**Comment by bobturneruk** [comment]
This needs to be checked against https://github.com/AFM-SPM/TopoStats/issues/10 before merging.

**Review by Jean-Du — APPROVED** [review]
The pip install seems to be working for me and I can run pwygwytracing.py normally. Would it be worth changing this into main.py and renamaing the topostats/tracing.py as topostats/pwygwytracing.py, for consistency reasons?

**Comment by bobturneruk** [comment]
Thanks @Jean-Du - that's a good point. I didn't want to change how users run TopoStats at all, but now we're targeting the pre-release `dev` branch, we could make that change and keep things consistent for the developers.

**Comment by bobturneruk** [comment]
@Jean-Du - how does this look, please? You can click the last commit to see the changes.

**Review by Jean-Du — CHANGES_REQUESTED** [review]
It's giving me the error message 
`IOError: [Errno 2] No such file or directory: 'default_config.ini'
No config file found named 'config.ini'`, presumably because pygwytracing.py and the config file are not under the same directory now?

**Comment by bobturneruk** [comment]
Thanks @Jean-Du - I'll need to fix this.

**Review by SylviaWhittle — APPROVED** [review]
Works fine for me. The decision to put the core python files in one folder is good, it makes the software more understandable and sensibly structured. 

(Ran using Docker. Windows 10 up-to-date)

**Comment by bobturneruk** [comment]
Thanks @SylviaWhittle ! Not sure about the config.ini thing, but *am* sure I should've put it in the package as it's necessary to run the software. I'll do some more work on it.

**Comment by bobturneruk** [comment]
Hi @Jean-Du - this should now be working. Also once it's installed it should be possible to run topostats in any folder, not just the repository. Please try again and mark changes addressed if it works!

**Review by Jean-Du — CHANGES_REQUESTED** [review]
I am still having issues with the config file. As it uses default_config.ini, which defaults the path to the current directory, this leads to an error as there are no spm files in the topostats directory.

**Comment by bobturneruk** [comment]
Hi @Jean-Du - should be running in the context of the directory in which you invoke the command. What directory are you in when you type `python -m topostats` please?

**Comment by Jean-Du** [comment]
@bobturneruk Directly running in a directory with spm files seems to work fine. I only had the issue when I was running it in the same directory as the script

**Review by Jean-Du — APPROVED** [review]
As long as the user follow the instructions in the readme it should work fine

**Comment by bobturneruk** [comment]
Thanks @Jean-Du !

**Pull request merged**
