### PR TITLE
Issue templates (done in `master` needed in `dev` also

### PR DESCRIPTION
**Pull request by bobturneruk**
I'm planning to merge this as admin as it was approved for master https://github.com/AFM-SPM/TopoStats/pull/93

### CODE REVIEW

**Comment by bobturneruk** [comment]
I need to rebase.

**Comment by bobturneruk** [comment]
Which I've duly messed up.

**Comment by bobturneruk** [comment]
That's better.

**Review by ns-rse — APPROVED** [review]

**Review by ns-rse — APPROVED** [review]
These look like they can be merged into `dev` and should be in anticipation of the big switch that will happen at some point.

**Pull request merged**
