### PR TITLE
Docker debug

### PR DESCRIPTION
**Pull request by bobturneruk**
Instructions and "utilities" for debugging topostats in a Python 2 Docker container, if you want to. e.g. if you're running Windows or macos and can't install it locally. I'd be keen for reviewers to feed back on whether they are able to get the debugger running using the new instructions, which are vscode specific.

### CODE REVIEW

**Comment by bobturneruk** [comment]
This is now ready for a check, if anyone has time.

**Review by SylviaWhittle — APPROVED** [review]
Works well for me! Is the addition of Codecov something I should be looking at too?

**Comment by bobturneruk** [comment]
@SylviaWhittle - codecov is being set up on the repo. It will make it easy to see which bits of code are covered by tests.

**Comment by bobturneruk** [comment]
I think this is helpful enough to merge, so I will. All this is just "scaffolding" while we move from python 2 to 3, and remove the Gwyddion dependency. Once we've done this, topostats should be easy enough to install and debug without docker.

**Pull request merged**
