### PR TITLE
Improve logging verbosity configuration

### PR DESCRIPTION
**Pull request by ns-rse**
Started investigating #381 and wanted to use `LOGGER.debug()` but hadn't configured this correctly in the first instance. This sets up the `LOGGER.setLevel()` conditional on the configuration value of `log_level` and introduces the command line option `-l/--log_level`. At the same time it negates the need for `warnings` and `quiet` in the configuration.

Validation and documentation updated to reflect this change.

When working on code and debugging you can now use `LOGGER.debug(f"[{self.filename}] [<function/method>] <MESSAGE>")` instead of `print(<MESSAGE>)` and see the output by using `run_topostats -l debug`.

### CODE REVIEW

**Review by SylviaWhittle — CHANGES_REQUESTED** [review]
This doesn't seem to work on my system. Perhaps it's an issue with my system?

I have tried setting the logging level in the config to `debug`, however no debug statements are printed, only `INFO` level ones. I have verified that they should be, for example the lines that you added (`175`, `176` in `filters.py`). I also added more debug level logging statements, verifying that it doesn't work on my system. 

I have verified that the line `LOGGER.setLevel("DEBUG")` runs, by placing a `print` just before it, so perhaps it's an issue internal to the logger?

I will continue to investigate in the meantime and let you know if I find anything.

**Comment by ns-rse** [comment]
Thanks for investigating this.

I do get the `debug` output when I run it locally with `run_topostats -l debug`.

Reading that thread suggests that perhaps I've not setup the `logging.StreamHandler()` correctly, as this [solution](https://stackoverflow.com/a/59705351/1444043) suggests setting `logging.basicConfig()` without using a handler could have adverse consequences and enable `debug()` for all modules called.

I doubt this is a Python version issue (I'm using `3.10.9`) but I get the following (it shouldn't make any difference that I modify `log_level` from the command line as all that dues is updated the config as per the first `INFO` message)...

```
❱ run_topostats -l debug
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Updated config config[log_level] : info > debug 
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] The YAML configuration file is valid.
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] The YAML plotting configuration file is valid.
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Configuration file loaded from      : None
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Scanning for images in              : /home/neil/tmp/topo_test
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Output directory                    : output
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Looking for images with extension   : .spm
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Images with extension .spm in /home/neil/tmp/topo_test : 1
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Thresholding method (Filtering)     : std_dev
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Thresholding method (Grains)        : std_dev
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Extracting image from /home/neil/tmp/topo_test/data/20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039.spm
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Loading image from : /home/neil/tmp/topo_test/data/20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039.spm
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] : Loaded image from : /home/neil/tmp/topo_test/data/20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039.spm
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] : Extracted channel Height
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] : Pixel to nm scaling : 1.953125
Processing images from /home/neil/tmp/topo_test, results are under output:   0%|                                | 0/1 [00:00<?, ?it/s][Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] Processing : 20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] : Median flattening without mask
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] : Plane tilt removal without mask
[Mon, 16 Jan 2023 11:32:40] [DEBUG   ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] [remove_tilt] medians_x   : [-7.479507876860165, -8.364529010918655, -8.904176043881154, -8.580387824103656, -8.073119613118909, -7.965190206526412, -7.922018443889417, -7.727745512022917, -7.652194927408164, -6.875103199942171, -6.616072624120182, -8.051533731800408, -9.022898391132895, -8.580387824103656, -8.48325135817041, -8.882590162562654, -8.720696052673905, -8.871797221903403, -8.548009002125905, -8.861004281244153, -8.051533731800408, -8.062326672459658, -8.332150188940911, -8.191841960370656, -7.101754953786422, -8.407700773555657, -8.526423120807404, -8.029947850481914, -5.87135971863194, -8.224220782348407, -6.17356205709093, -8.202634901029914, -8.062326672459658, -8.332150188940911, -6.37862792961668, -7.9867760878449126, -7.641401986748921, -8.342943129600155, -8.051533731800408, -8.040740791141165, -7.749331393341418, -7.555058461474918, -7.91122550323016, -7.792503155978412, -6.86431025928292, -7.490300817519415, -7.7169525713636595, -7.393164351586169, -7.673780808726665, -7.706159630704409, -7.835674918615414, -7.619816105430413, -7.641401986748921, -6.486557336209177, -7.328406707630666, -7.835674918615414, -7.490300817519415, -7.263649063675171, -7.263649063675171, -5.968496184565186, -6.648451446097926, -7.23127024169742, -5.69867266808394, -6.497350276868428, -6.86431025928292, -6.85351731862367, -6.3570420482981795, -6.292284404342677, -6.033253828520682, -6.421799692253682, -6.734794971371922, -6.670037327416427, -6.583693802142424, -6.562107920823923, -6.637658505438676, -6.076425591157683, -6.389420870275924, -6.713209090053429, -6.281491463683427, -6.36783498895743, -6.249112641705683, -6.454178514231426, -6.270698523024183, -6.249112641705683, -6.292284404342677, -6.227526760387182, -5.7310514900616845, -6.151976175772436, -6.054839709839182, -5.558364439513692, -5.763430312039436, -5.957703243905936, -5.9469103032466855, -6.259905582364933, -5.50439973621744, -6.162769116431679, -5.69867266808394, -6.130390294453935, -6.011667947202181, -5.353298566987942, -5.774223252698686, -6.054839709839182, -5.709465608743184, -5.569157380172943, -5.536778558195184, -5.299333863691697, -5.040303287869694, -5.655500905446939, -4.910787999958696, -4.554620958203454, -5.256162101054688, -5.472020914239689, -5.418056210943437, -5.763430312039436, -5.547571498854435, -5.472020914239689, -5.536778558195184, -4.921580940617947, -5.342505626328691, -5.234576219736194, -5.525985617535941, -5.266955041713938, -5.234576219736194, -5.169818575780692, -4.856823296662444, -4.468277432929451, -4.44669155161095, -2.9680586812937158, -4.81365153402545, -3.3350186637082153, -5.299333863691697, -5.180611516439942, -4.953959762595698, -4.090524509855708, -4.5654138988626976, -4.435898610951707, -4.457484492270201, -4.122903331833452, -4.2632115604037075, -4.479070373588701, -4.61937860215895, -4.014973925240955, -4.068938628537207, -4.166075094470454, -4.0473527472187065, -4.241625679085207, -4.586999780181198, -4.414312729633199, -4.068938628537207, -3.971802162603961, -3.6695998241449566, -3.7235645274412086, -3.464533951619213, -2.978851621952966, -3.2918469010712172, -3.6048421801894612, -2.169381072509225, -3.0436092659084686, -2.7629928087679723, -1.8671787340502348, -2.9140939779974673, -3.4105692483229646, -3.594049239530211, -3.712771586781958, -3.7775292307374606, -3.518498654915465, -3.0759880878862162, -3.227089257115715, -2.8169575120642207, -2.79537163074572, -3.1947104351379636, -2.9464727999752185, -3.57246335821171, -2.719821046130974, -3.4429480703007123, -3.119159850523218, -2.935679859315968, -3.140745731841715, -2.719821046130974, -2.449997529649721, -2.482376351627476, -3.1299527911824647, -2.903301037338217, -3.097573969204717, -1.7160775648207327, -2.860129274701219, -2.525548114264474, -2.568719876901472, -1.996694021961229, -2.385239885694226, -2.3096893010794766, -3.0436092659084686, -2.169381072509225, -2.741406927449468, -2.709028105471724, -1.7700422681169812, -2.1585881318499744, -2.3096893010794766, -2.860129274701219, -2.676649283493969, -2.331275182397974, -2.2017598944869796, -1.996694021961229, -2.0506587252574775, -1.791628149435482, -1.726870505479983, -1.899557556027979, -1.6621128615244807, -2.1801740131684753, -0.5072682109847442, -2.093830487894479, -1.6729058021837346, -1.6944916835022354, -1.8455928527317305, -1.5757693362504845, -0.9281928966954922, -0.3129952791182511, 0.021585881318497258, 0.3561670417552456, 0.18347999120724978, -0.4640964483477461, -1.7052846241614787, -1.8671787340502348, -1.748456386798484, -1.8779716747094781, -1.370703463724734, -1.1872234725174877, -1.2411881758137397, -1.2843599384507378, -1.2951528791099882, -1.6621128615244807, -0.7555058461474928, -1.2088093538359885, -1.1980164131767381, -1.1764305318582409, -0.7231270241697452, 0.4748893890069894, -0.7555058461474928, -0.9389858373547426, -0.8526423120807394, -0.1079294065925005, 0.010792940659250405, -0.8958140747177445, -1.2843599384507378, -1.1656375911989905, -1.1872234725174877, -0.733919964828992, -0.6799552615327435, -0.949778778013993, 0.04317176263699807, -0.8634352527399898, 0.12951528791099776, -0.3885458637329968, -0.3885458637329968, 0.5936117362587403, -0.2698235164812459, -0.3237882197775015, 0.07555058461474573, 0.30220233845899713, -0.3885458637329968, -0.06475764395550243, -0.16189410988874897, -0.17268705054799938, 0.04317176263699807, 0.2158588131849939, 0.5612329142809926, 0.4640964483477461, -0.07555058461475284, 0.17268705054799582, 0.1403082285702446, -0.30220233845899713, -0.010792940659250405, 0.6259905582364915, 0.2806164571404963, 0.5180611516439946, 0.5936117362587403, 0.18347999120724978, 0.25903057582199196, 0.8634352527399898, 0.6151976175772411, 0.43171762636999134, 1.0145364219694848, 0.6259905582364915, 0.4748893890069894, 0.4964752703254902, 0.9497787780139859, 1.2951528791099811, 0.841849371421489, 1.2843599384507307, 0.992950540650984, 1.0253293626287387, 0.9173999560362383, 1.4246681670209824, 1.0577081846064829, 1.0685011252657368, 1.0792940659249872, 1.2951528791099811, 1.0792940659249872, 1.2411881758137326, 1.208809353835985, 1.7160775648207292, 1.0145364219694848, 1.1548446505397365, 1.1116728879027349, 1.208809353835985, 1.370703463724734, 1.3275317010877359, 1.5110116922949786, 1.1872234725174842, 2.6658563428347186, 1.5433905142727333, 1.4354611076802328, 1.1548446505397365, 3.086781028545463, 1.5002187516357317, 1.4030822857024816, 1.4894258109764813, 1.672905802183731, 1.7268705054799796, 2.0614516659167244, 1.9535222593242274, 5.148232694462191, 1.6081481582282322, 4.522242136225696, 1.8779716747094781, 2.3312751823979703, 1.521804632954229, 2.007486962620476, 2.3528610637164746, 2.0722446065759783, 2.1801740131684753, 1.8563857933909738, 3.6803927648042034, 2.0722446065759783, 2.3960328263534727, 2.244931657123974, 2.32048224173872, 2.2233457758054733, 2.255724597783221, 2.449997529649721, 2.719821046130967, 3.0220233845899642, 2.3960328263534727, 2.849336334041965, 2.3744469450349683, 2.244931657123974, 2.6118916395384666, 3.2162963164564644, 2.51475517360522, 3.313432782389711, 3.3026398417304605, 2.762992808767965, 2.8817151560197125, 2.9033010373382133, 2.762992808767965, 2.935679859315961, 3.421362188982208, 3.1947104351379636, 3.464533951619206, 3.2162963164564644, 3.820700993374455, 3.399776307663707, 3.054402206567712, 3.8746656966707036, 3.777529230737457, 3.7991151120559543, 3.464533951619206, 3.777529230737457, 3.7559433494189562, 3.658806883485706, 3.9070445186484513, 3.583256298870957, 3.388983367004464, 4.047352747218703, 3.583256298870957, 3.540084536233959, 3.7451504087597023, 3.6048421801894577, 3.6372210021672053, 3.5292915955747084, 6.540522039505426, 3.8314939340337055, 3.928630399966952, 3.734357468100452, 3.777529230737457, 3.863872756011453, 5.439642092261934, 3.507705714256204, 5.709465608743184, 3.712771586781958, 4.457484492270197, 5.418056210943437, 4.586999780181195, 4.457484492270197, 4.457484492270197, 4.694929186773695, 4.004180984581705, 3.928630399966952, 4.856823296662444, 4.770479771388445, 4.846030356003194, 4.651757424136697, 4.6733433054551945, 4.360348026336947, 4.932373881277194, 4.748893890069947, 5.385677388965686, 5.22378327907694, 5.299333863691686, 5.439642092261934, 5.180611516439939, 4.986338584573442, 5.094267991165939, 5.21299033841769, 5.666293846106182, 5.2453691603954375, 5.159025635121438, 4.781272712047691, 6.443385573572176, 4.522242136225696, 4.932373881277194, 6.4110067515944245, 5.180611516439939, 5.720258549402434, 5.677086786765432, 5.5691573801729355, 5.99008206588368, 5.472020914239685, 5.698672668083933, 5.731051490061681, 5.266955041713938, 6.626865564779422, 5.612329142809934, 5.4072632702841865, 7.101754953786418, 5.849773837313432, 6.151976175772425, 5.709465608743184, 5.7742232526986825, 6.4110067515944245, 6.259905582364929, 6.1411832351131785, 5.957703243905929, 6.518936158186925, 6.626865564779422, 6.432592632912925, 6.367834988957426, 6.270698523024176, 6.389420870275924, 7.231270241697416, 7.1449267164234165, 7.015411428512419, 6.659244386757173, 6.6160726241201715, 6.281491463683427, 6.896689081260668, 6.907482021919918, 6.929067903238419, 6.885896140601421, 7.080169072467918, 7.274442004334414, 7.155719657082667, 6.896689081260668, 6.572900861483173, 6.4110067515944245, 7.3068208263121655, 7.263649063675167, 7.112547894445669, 6.85351731862367, 7.242063182356667, 7.05858319114942, 6.8319314373051725, 7.274442004334414, 7.05858319114942, 6.691623208734924, 6.648451446097923, 7.73853845268216, 6.896689081260668, 7.6737808087266615, 7.069376131808667, 6.76717379334967, 6.648451446097923, 7.436336114223167, 6.86431025928292, 7.447129054882414, 7.296027885652915, 7.555058461474911, 7.889639621911659, 8.073119613118905, 7.846467859274657, 7.317613766971416, 7.209684360378915, 7.360785529608414, 7.857260799933911, 7.975983147185659, 7.9867760878449054, 8.5264231208074, 7.857260799933911, 7.598230224111912, 7.857260799933911, 8.148670197733658, 8.353736070259401, 7.609023164771159, 8.137877257074408, 8.655938408718399, 8.353736070259401, 8.202634901029906, 8.645145468059148, 7.943604325207907, 7.889639621911659, 8.580387824103653, 8.5911807647629]
[Mon, 16 Jan 2023 11:32:40] [DEBUG   ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] [remove_tilt] medians_y   : [0.0]
[Mon, 16 Jan 2023 11:32:40] [INFO    ] [topostats] [20220811_nickedcatenane_6ng_nicl2_mgcl2.0_00039] : x-polyfit 1st order: [ 0.03401922 -8.87987985]
/home/neil/.virtualenvs/topostats/lib/python3.10/site-packages/numpy/lib/polynomial.py:667: RuntimeWarning: invalid value encountered in divide
```

**Comment by SylviaWhittle** [comment]
Ah yes I see. Are you trying / have you tried the solution that they present as an alternative to `logging.basicConfig(level=logging.DEBUG, format='%(message)s')`:

```
import logging

logger = logging.getLogger('MyLogger')
handler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
```

I have just tried this and it also solves the issue, while not unintentionally setting other loggers' levels.

**Comment by ns-rse** [comment]
I've added unit-tests to check the various logging levels as well as a regression test that checks `DEBUG` log-level messages returned by `run_topostats`.

One thing I found was that any `DEBUG` logging info that is generated by `process_scan()` will not appear in the `pytest` `caplog` because it doesn't appear to yet handle multi-processing (see [#3037 caplog fixture: capture log records from another process](https://github.com/pytest-dev/pytest/issues/3037).

Thus the regression test that checks for `DEBUG` output has necessarily introduces some `LOGGER.debug()` statements to `run_topostats()`, but these will only ever be seen if the configuration has `log_level: debug` or the command line option `-l debug` is used.

**Review by SylviaWhittle — APPROVED** [review]
This successfully works as intended on my M1 machine (the tests run successfully too), so it seems you have solved the annoying issue with logging 🎉 

The logging code makes more sense to me now too

image

Looks good to me!

**Pull request merged**
