### PR TITLE
Adding linting configurations; applying black to topostats/

### LINKED ISSUE #245: Standardise linting parameters for black and pylint
**Is your feature request related to a problem? Please describe.**

Going forward we would like to adopt [linting](https://rse.shef.ac.uk/blog/2022-04-19-linting/) across the project using initially [black](https://black.readthedocs.io/en/stable/), [pylint](https://pylint.pycqa.org/en/latest/) and [flake8](https://flake8.pycqa.org/en/latest/).

**Describe the solution you'd like**

To standardise configuration across all contributors the configuration options for each linter should be included within the project itself. [black](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file) can be configured using options in the projects `pyproject.toml`, [flake8](https://flake8.pycqa.org/en/latest/user/configuration.html) reads from `setup.cfg`, `tox.ini` or `.flake8` within the project root, although there is a monkey patch [pyproject-flake](https://pypi.org/project/pyproject-flake8/) that will connect it to read configuration from `pyproject.toml`.

`pylint` has considerably more options available but also [supports configuration](https://pylint.pycqa.org/en/latest/user_guide/usage/run.html#command-line-options) via `.pylintrc` and a also `pyproject.toml`  with sections beginning `[tool.pylint.]` see documentation for details.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by ns-rse**
Resolves #245 

Adds configurations for `flake8`, `black` and `pylint` to the project.

In testing I ran `black topostats/` and it updated some files there too.

### CODE REVIEW

**Comment by bobturneruk** [comment]
I've seen this and it's on my to-do list.

**Comment by SylviaWhittle** [comment]
Hi @ns-rse, this looks like really good stuff, though I'm a little unsure as to the correct process for trying it out given that a lot of the configs that we use, I have engrained in the settings of VSCode. 

I could set up a VM and try installing VSCode or another IDE and see if these changes in the repo causes the correct configuration to be used for the linter, formatter etc?

**Comment by ns-rse** [comment]
Hi @SylviaWhittle 

I think the way to do this might be through [workspace settings](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings) which creates a `.vscode/settings.json` directory/file for settings specific to that project.

I'm not sure of the exact configuration options, but `black` should pickup the settings from `pyproject.toml` automatically (it would if it were run on the command line at least). For `pylint` it may be necessary to run with `cd ~/path/to/TopoStats/ && pylint --rc-file=.pylintrc topostats` to get it to use the configuration file.

As a longer term goal introducing [pre-commit](https://pre-commit.com/) would get round this to a large extent since its configuration and virtual environments are used, but I didn't want to jump straight to using that just yet.

**Review by bobturneruk — APPROVED** [review]
This is a positive change to ensure that, where people are using linting / auto-formatting with pylint / black, they're using standardised tools with standardised settings. 

I think there's a bit of work to get this going in vscode on windows 10, at least. This would be making a `.pylintrc` file (which would be best committed to the repo, made like this `pylint --generate-rcfile | Out-File -Encoding utf8 .pylintrc`). I think this is worth doing anyway. Also tuning of user and workspace settings to trigger linting / formatting on save - this is a user specific thing not for the repo, but e.g. in the repo folder `.vscode/settings.json`:

```
{
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,
    "python.linting.lintOnSave": true,
    "python.formatting.provider": "black",
    "editor.formatOnSave": true
}
```

Periodically deleting user settings is an invigorating experience (all kinds of things get stored in there that can interfere with project-specific stuff).

**Pull request merged**
